<?php

namespace My\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitEnchereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitEnchereRepository extends EntityRepository
{
}
